version: '3'
services:
  control-node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: control-node
    networks:
      ansible-networks:
        ipv4_address: 10.0.15.10
    volumes:
      - ./ansible:/home/ansible/ansible
    tty: true

  target-node1:
    build:
      context: .
      dockerfile: Dockerfile.target
    container_name: target-node1
    networks:
      ansible-networks:
        ipv4_address: 10.0.15.101
    tty: true

  target-node2:
    build:
      context: .
      dockerfile: Dockerfile.target
    container_name: target-node2
    networks:
      ansible-networks:
        ipv4_address: 10.0.15.102
    tty: true

networks:
  ansible-networks:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.15.0/24
          gateway: 10.0.15.1
